package com.phantomcode.app.ui.theme

import androidx.compose.ui.graphics.Color

/**
 * Paleta visual Cyber-Phantom.
 * Fonte de verdade: Documento Mestre §10.1 (tokens HEX).
 */
data class PhantomPalette(
    val name: String,
    val background: Color,
    val surface: Color,
    val surfaceAlt: Color,
    val accentPrimary: Color,
    val accentBright: Color,
    val accentSecondary: Color,
    val border: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val error: Color,
    val success: Color,
    val isDark: Boolean = true,
)

/** Presets de tema (D10) — selecionáveis em Settings → Aparência & Temas. */
enum class PhantomPreset(val id: String, val label: String) {
    PHANTOM("phantom", "Phantom"),
    DEEP_SLATE("deep_slate", "Deep Slate"),
    MATRIX("matrix", "Matrix"),
    DRACULA("dracula", "Dracula"),
    NORD("nord", "Nord"),
    SOLARIZED("solarized", "Solarized"),
    LIGHT("light", "Light Soft"),
    CUSTOM("custom", "Custom"),
}

val PhantomPalettes: Map<PhantomPreset, PhantomPalette> = mapOf(
    PhantomPreset.PHANTOM to PhantomPalette(
        name = "Cyber-Phantom",
        background = Color(0xFF000000),
        surface = Color(0xFF121212),
        surfaceAlt = Color(0xFF1E1E1E),
        accentPrimary = Color(0xFF9F4DFF),
        accentBright = Color(0xFFD34DFF),
        accentSecondary = Color(0xFF00FFFF),
        border = Color(0xFF4B5563),
        textPrimary = Color(0xFFE5E7EB),
        textSecondary = Color(0xFF888888),
        error = Color(0xFFFF3366),
        success = Color(0xFF00FF9F),
    ),
    PhantomPreset.DEEP_SLATE to PhantomPalette(
        name = "Deep Slate",
        background = Color(0xFF0E0E14),
        surface = Color(0xFF17171F),
        surfaceAlt = Color(0xFF23232E),
        accentPrimary = Color(0xFF8B7CFF),
        accentBright = Color(0xFFA99EFF),
        accentSecondary = Color(0xFF9FB4FF),
        border = Color(0xFF2E2E3A),
        textPrimary = Color(0xFFE2E2EA),
        textSecondary = Color(0xFF7E7E8C),
        error = Color(0xFFFF6B7D),
        success = Color(0xFF6EE7B7),
    ),
    PhantomPreset.MATRIX to PhantomPalette(
        name = "Matrix",
        background = Color(0xFF0A0A0A),
        surface = Color(0xFF101210),
        surfaceAlt = Color(0xFF1A1F1A),
        accentPrimary = Color(0xFF00FF41),
        accentBright = Color(0xFF66FF99),
        accentSecondary = Color(0xFF00C853),
        border = Color(0xFF1E5B2E),
        textPrimary = Color(0xFFC8FFC8),
        textSecondary = Color(0xFF5E9E6E),
        error = Color(0xFFFF0055),
        success = Color(0xFF00FF41),
    ),
    PhantomPreset.DRACULA to PhantomPalette(
        name = "Dracula",
        background = Color(0xFF282A36),
        surface = Color(0xFF21222C),
        surfaceAlt = Color(0xFF343746),
        accentPrimary = Color(0xFFBD93F9),
        accentBright = Color(0xFFD6B9FF),
        accentSecondary = Color(0xFF8BE9FD),
        border = Color(0xFF44475A),
        textPrimary = Color(0xFFF8F8F2),
        textSecondary = Color(0xFF6272A4),
        error = Color(0xFFFF5555),
        success = Color(0xFF50FA7B),
    ),
    PhantomPreset.NORD to PhantomPalette(
        name = "Nord",
        background = Color(0xFF2E3440),
        surface = Color(0xFF3B4252),
        surfaceAlt = Color(0xFF434C5E),
        accentPrimary = Color(0xFF88C0D0),
        accentBright = Color(0xFFB8DCE6),
        accentSecondary = Color(0xFF81A1C1),
        border = Color(0xFF4C566A),
        textPrimary = Color(0xFFECEFF4),
        textSecondary = Color(0xFF9AA5B5),
        error = Color(0xFFBF616A),
        success = Color(0xFFA3BE8C),
    ),
    PhantomPreset.SOLARIZED to PhantomPalette(
        name = "Solarized Dark",
        background = Color(0xFF002B36),
        surface = Color(0xFF073642),
        surfaceAlt = Color(0xFF0A4552),
        accentPrimary = Color(0xFF268BD2),
        accentBright = Color(0xFF62B3E5),
        accentSecondary = Color(0xFF2AA198),
        border = Color(0xFF586E75),
        textPrimary = Color(0xFF93A1A1),
        textSecondary = Color(0xFF6C7B80),
        error = Color(0xFFDC322F),
        success = Color(0xFF859900),
    ),
    PhantomPreset.LIGHT to PhantomPalette(
        name = "Light Soft",
        background = Color(0xFFF8F8F8),
        surface = Color(0xFFFFFFFF),
        surfaceAlt = Color(0xFFEEEEF3),
        accentPrimary = Color(0xFF6B21A8),
        accentBright = Color(0xFF8B3FD8),
        accentSecondary = Color(0xFF0891B2),
        border = Color(0xFFE5E7EB),
        textPrimary = Color(0xFF1F2937),
        textSecondary = Color(0xFF6B7280),
        error = Color(0xFFDC2626),
        success = Color(0xFF059669),
        isDark = false,
    ),
)
